Support font.math.*DeviceTable as indexable object
mf2vec-dev/fontforge pull request #1
Opened 2024-03-29 16:33 UTC by iorsh

2024-03-30 14:38 UTC, mf2vec-dev requested changes
Thank you very much for looking into this. I did some testing and it seems to work.

Besides the comments, please also update `fontforge.rst`.

The only thing that is a bit strange is the behavior of something like the following. I understand why this happens, but this may not be the most intuitive behavior for some users.

```py
font.math.MathLeadingDeviceTable[10] = 1
a = font.math.MathLeadingDeviceTable
print(font.math.MathLeadingDeviceTable[10]) # 1
print(a[10]) # 1
print('')

a[10] = 2
print(font.math.MathLeadingDeviceTable[10]) # 2
print(a[10]) # 2
print('')

font.math.SpaceAfterScriptDeviceTable = a
a[10] = 3
print(font.math.MathLeadingDeviceTable[10]) # 3
print(a[10]) # 3
print(font.math.SpaceAfterScriptDeviceTable[10]) # 2
```

(`a = font.math.*DeviceTable` by reference and `font.math.*DeviceTable = a` by value)

I'm not sure if this can or should be changed. However, it's fine for me to merge it with this behavior if there is no easy alternative.

2024-03-30 14:38 UTC, mf2vec-dev commented on fontforge/python.c
>  static PyObject *PyFFMath_Str(PyFF_Math *self) {
This function (`PyFFMath_Str`) is used for both, device table objects and math objects. Please use a separate function with a suitable string for the new device tables.

2024-03-30 14:38 UTC, mf2vec-dev commented on fontforge/python.c
>  }
You may want to move this function (`SFGetMathTable`) down to the math section.

2024-03-30 14:38 UTC, mf2vec-dev commented on fontforge/python.c
> +    uint16_t px, low, high;
`low` and `high` are unused
```suggestion
    uint16_t px;
```

2024-03-30 14:38 UTC, mf2vec-dev commented on fontforge/python.c
> +    PyFF_MathDeviceIndexAssign	/* subscript assign */
I'm getting incompatible pointer types warnings here.

2024-03-30 14:38 UTC, mf2vec-dev commented on fontforge/python.c
> +	px = PyLong_AsLong(index);
Don't mix tabs and spaces for indentation, or at least use one tab for one level of indentation (it looks like you are using tabs for 8 spaces while indentaitons are 4 spaces). Also several times below.

2024-03-30 14:38 UTC, mf2vec-dev commented on fontforge/python.c
> +	PyErr_Format(PyExc_TypeError, "Device correction value must be an integer or None" );
I tested setting to None, but it doesn't work: `font.math.MathLeadingDeviceTable[10] = None`
Remove from error message or fix support for None (and add to test).

2024-03-30 14:38 UTC, mf2vec-dev commented on fontforge/python.c
> +    NULL,                      /* tp_dict */
`__dict__` support would be great.

2024-03-30 14:38 UTC, mf2vec-dev commented on tests/test1019.py
Please add a check for `len()`.

2024-03-30 14:38 UTC, mf2vec-dev commented on tests/test1019.py
> +assert font.math.SpaceAfterScriptDeviceTable != {12: 2}
Do you need both? I think they are equivalent.

2024-04-04 20:38 UTC, iorsh commented
> The only thing that is a bit strange is the behavior of something like the following. I understand why this happens, but this may not be the most intuitive behavior for some users.
> 
> ```python
> font.math.MathLeadingDeviceTable[10] = 1
> a = font.math.MathLeadingDeviceTable
> print(font.math.MathLeadingDeviceTable[10]) # 1
> print(a[10]) # 1
> print('')
> 
> a[10] = 2
> print(font.math.MathLeadingDeviceTable[10]) # 2
> print(a[10]) # 2
> print('')
> 
> font.math.SpaceAfterScriptDeviceTable = a
> a[10] = 3
> print(font.math.MathLeadingDeviceTable[10]) # 3
> print(a[10]) # 3
> print(font.math.SpaceAfterScriptDeviceTable[10]) # 2
> ```
> 
> (`a = font.math.*DeviceTable` by reference and `font.math.*DeviceTable = a` by value)
> 
> I'm not sure if this can or should be changed. However, it's fine for me to merge it with this behavior if there is no easy alternative.

I think we can resolve this ambiguity by forcing user into explicit copy:
```
a = font.math.MathLeadingDeviceTable
a[10] = 3
font.math.SpaceAfterScriptDeviceTable = a # Error: direct assignment to another device table not allowed
font.math.SpaceAfterScriptDeviceTable = a.copy() # OK: data explicitly copied from a into another device table
```
Alternatively, we can just forbid copying into another device table altogether.

@skef, what do you think about the desired API?

2024-04-04 20:52 UTC, iorsh commented on fontforge/python.c
>  }
It's used right away in `PyFF_MathDeviceLength()` and further, so a forward declaration would be needed instead. So I think to keep it here.

2024-04-04 21:04 UTC, iorsh commented on fontforge/python.c
> +	px = PyLong_AsLong(index);
The existing code is mostly formatted with 8-tab and 4-indent, so the tabs are indeed 8 spaces, but sometimes there is half-tab which is made with 4 spaces. I'm not sure I can do much about it, no modern code editor supports such indentation.

2024-04-04 21:16 UTC, iorsh commented on fontforge/python.c
> +    NULL,                      /* tp_dict */
Currently `__dict__` is not supported in any FF Python object, so I think it would be better added uniformly if we ever decide to support it.

2024-04-04 21:20 UTC, iorsh commented on tests/test1019.py
> +assert font.math.SpaceAfterScriptDeviceTable != {12: 2}
`==` and `!=` are separate operations - see **int op** argument in `PyFF_MathDeviceTableCompare()`

2024-04-04 21:35 UTC, iorsh commented on fontforge/python.c
>  }
Done

2024-04-04 21:35 UTC, iorsh commented on fontforge/python.c
> +    PyFF_MathDeviceIndexAssign	/* subscript assign */
Fixed

2024-04-04 21:36 UTC, iorsh commented on fontforge/python.c
> +	PyErr_Format(PyExc_TypeError, "Device correction value must be an integer or None" );
Fixed to support None assignment

2024-04-04 21:36 UTC, iorsh commented on tests/test1019.py
Added

2024-04-06 10:22 UTC, mf2vec-dev requested changes

2024-04-06 10:22 UTC, mf2vec-dev commented on fontforge/python.c
> +	PyErr_Format(PyExc_TypeError, "Device correction value must be an integer or None" );
I'm still getting an error with `font.math.MathLeadingDeviceTable[10] = None`:
`TypeError: Device correction value must be an integer or None`

I think your recent changes refer to something like `font.math.MathLeadingDeviceTable = None`, i.e. without subscription `[10]`, but the error message when using subscription indicates that `None` is supported.
Could you please double check this?

2024-04-06 10:22 UTC, mf2vec-dev commented on tests/test1019.py
> +assert font.math.AxisHeightDeviceTable == {}
`font.math.AxisHeightDeviceTable` never contained values in this test, so if assigning `None` doesn't work (e.g. if it would have no effect), the test wouldn't catch it. Your implementation works fine, but to make the test check what it should check, you may want to assign a value before assigning `None`.
```suggestion
font.math.AxisHeightDeviceTable = {10: -1}
font.math.AxisHeightDeviceTable = None
assert font.math.AxisHeightDeviceTable == {}
```

2024-04-06 10:22 UTC, mf2vec-dev commented on fontforge/python.c
> +    NULL,                      /* tp_dict */
I agree that it should be consistent. But I think it would be good if there was some kind of Python interface to check which font sizes are actually stored in the table. 

I think the only solution with the current interface is to loop through all possible font sizes and check for non-zero. In my opinion, there should be a more elegant way to do this.

2024-04-06 18:25 UTC, iorsh commented on fontforge/python.c
> +	PyErr_Format(PyExc_TypeError, "Device correction value must be an integer or None" );
You are right, I missed it. Fixed now.

2024-04-06 18:32 UTC, iorsh commented on fontforge/python.c
> +    NULL,                      /* tp_dict */
`__dict__` is not about dictionary-like behavior to the object. It allows to list class members and member methods. In order to loop through the values, we need to implement a separate iterator object - see `PyFF_LayerIterType` for layer iterator. This is rather straightforward, but I'm not sure I have time for this right now.

2024-04-06 18:32 UTC, iorsh commented on tests/test1019.py
> +assert font.math.AxisHeightDeviceTable == {}
Right, done.

2024-04-17 17:35 UTC, skef commented
>  I think we can resolve this ambiguity by forcing user into explicit copy:

What would be the disadvantage of always copying on assignment ourselves in this case? Would that lead to too much confusion about what was by value and what was by reference?

```
font.math.SpaceAfterScriptDeviceTable = a # Error: direct assignment to another device table not allowed
font.math.SpaceAfterScriptDeviceTable = a.copy() # OK: data explicitly copied from a into another device table
```
Is this even possible to differentiate at the C-API level (genuine question)? I would have thought both would just look the same internally.

2024-04-20 17:39 UTC, iorsh commented
Copy on assignment is inherently non-Pythonic, so the following would be confusing:
```
# User unknowingly creating a detached copy of device table
a = font.math.MathLeadingDeviceTable

# Assigning element inside a
a[10] = 1

# Expecting font.math.MathLeadingDeviceTable to change
print(font.math.MathLeadingDeviceTable[10]) # Not "1" here
```

For my `copy()`-based proposal the differentiation would technically be as follows:
```
# a is a FontForge-specific object PyFF_MathDeviceTable, which has no data,
# but only reference to font and specific device table inside it.
a = font.math.MathLeadingDeviceTable

# Assignment of PyFF_MathDeviceTable object to other device table fails
font.math.SpaceAfterScriptDeviceTable = a # Error: direct assignment to another device table not allowed

# a.copy() copies data into a plain dictionary like {10: 1, 12: -1},
# disconnected from the specific font and the specific device table
#
# Assignment of plain dictionary to other device table succeeds.
font.math.SpaceAfterScriptDeviceTable = a.copy() # OK: assignment of plain data to device table allowed
```

2024-07-12 21:36 UTC, iorsh commented
@mf2vec-dev, please review

2024-07-27 17:18 UTC, mf2vec-dev approved these changes
Thanks for implementing the iterator.

In light of the discussion in this PR and in fontforge#5348, I'm fine with the current approach.

2024-07-27 17:20 UTC, merged